/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-01-13 13:11:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.service.PrincipalService;
import com.entity.PrincipalEntity;
import com.sun.xml.internal.bind.v2.schemagen.xmlschema.List;

public final class Test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>学生交流平台-校长留言板</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/public.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

PrincipalService ps = new PrincipalService();
ps.getMessage(new PrincipalEntity());

      out.write("\r\n");
      out.write("    <div id=\"middle\">\r\n");
      out.write("\r\n");
      out.write("    <div id=\"top\">\r\n");
      out.write("        <a href=\"http://www.cqwu.net\"><img src=\"img/logo1.png\" alt=\"Logo\"></a>\r\n");
      out.write("        <img src=\"img/logo2.png\" alt=\"Logo\">\r\n");
      out.write("        <form class=\"search\">\r\n");
      out.write("            <input id=\"input\" type=\"text\" placeholder=\"在此输入您要搜索的内容\" required value=\"\">\r\n");
      out.write("            <a class=\"clear\" href=\"\" ></a>\r\n");
      out.write("            <div id=\"choose\">\r\n");
      out.write("                <select name=\"search\" style=\"width: 50px;height: 25px;\">\r\n");
      out.write("                    <option value=\"\">编号</option>\r\n");
      out.write("                    <option value=\"\">标题</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button id=\"btn_search\"><span id=\"span_search\"><img src=\"img/search.png\" style=\"width: 15px;\"></span></button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"clrli\"><a class=\"clra\" href=\"index.jsp\">首页</a></li>\r\n");
      out.write("            <li class=\"clrli\"><a class=\"clra\" href=\"Principal.jsp\">校长留言板</a></li>\r\n");
      out.write("            <li class=\"clrli\"><a class=\"clra\" href=\"Department.jsp\">部门留言板</a></li>\r\n");
      out.write("            <li class=\"clrli\"><a class=\"clra\" href=\"College.jsp\">学院留言板</a></li>\r\n");
      out.write("            <li class=\"clrli\"><a class=\"clra\" href=\"Message.jsp\">发表留言</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"cb\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"picture\">\r\n");
      out.write("        <img src=\"img/picture.jpg\" alt=\"picture1\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"message_Principal\">\r\n");
      out.write("            <div class=\"bluebar\">\r\n");
      out.write("                <a><img src=\"img/principal.png\"> 校长留言板</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"greycontent_visiable\">\r\n");
      out.write("                <div class=\"message_bottom_left\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"clrli\"><a class=\"clra\" href=\"#\">书记留言板</a></li>\r\n");
      out.write("                        <li class=\"clrli\"><a class=\"clra\" href=\"#\">校长留言板</a></li>\r\n");
      out.write("                        <li class=\"clrli\"><a class=\"clra\" href=\"#\">分管校长留言板</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fl\">\r\n");
      out.write("                <form name=\"form\" id=\"form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/servlet/LoginServleta\" method=\"post\">\r\n");
      out.write("                    <table width=\"850px\" style=\"margin-left: 15px\"><tr class=\"single\">\r\n");
      out.write("                            <td width=\"60px\">留言编号</td>\r\n");
      out.write("                            <td>留言标题</td>\r\n");
      out.write("                            <td width=\"200px\">留言时间</td>\r\n");
      out.write("                            <td width=\"60px\">点击率</td>\r\n");
      out.write("                            <td width=\"70px\">详情查看</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    ");
 
                    for(int i=0;i<=13;i++){
                    
      out.write("\r\n");
      out.write("                    \t");
if((i%2)==0){
      out.write("\r\n");
      out.write("                   \t\t\t<tr class=\"double\">\r\n");
      out.write("                            <td width=\"80px\">");
 out.print(ps.list_id.get(i));
      out.write("</td>\r\n");
      out.write("                            <td>");
 out.print(ps.list_title.get(i));
      out.write("</td>\r\n");
      out.write("                            <td width=\"110px\">");
 out.print(ps.list_m_time.get(i));
      out.write("</td>\r\n");
      out.write("                            <td width=\"30px\">");
 out.print(ps.list_click.get(i));
      out.write("</td>\r\n");
      out.write("                            <td width=\"70px\">详情</td>\r\n");
      out.write("                      \t\t</tr>\r\n");
      out.write("                    \t");
}else{
      out.write("\r\n");
      out.write("                   \t\t\t<tr class=\"single\">\r\n");
      out.write("                            <td width=\"80px\">");
 out.print(ps.list_id.get(i));
      out.write("</td>\r\n");
      out.write("                            <td>");
 out.print(ps.list_title.get(i));
      out.write("</td>\r\n");
      out.write("                            <td width=\"110px\">");
 out.print(ps.list_m_time.get(i));
      out.write("</td>\r\n");
      out.write("                            <td width=\"30px\">");
 out.print(ps.list_click.get(i));
      out.write("</td>\r\n");
      out.write("                            <td width=\"70px\">详情</td>\r\n");
      out.write("                      \t\t</tr>\r\n");
      out.write("                    \t");
}
      out.write("\r\n");
      out.write("                    ");
 
                    }
                    
      out.write("\r\n");
      out.write("                    </table>\r\n");
      out.write("                </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cb\"></div>\r\n");
      out.write("\r\n");
      out.write("                <div style=\"margin: 20px 0;\">\r\n");
      out.write("                    <input type=\"submit\" value=\"首 页\" class=\"button\">\r\n");
      out.write("                    <input type=\"submit\" value=\"上一页\" class=\"button\">\r\n");
      out.write("                    <input type=\"submit\" value=\"下一页\" class=\"button\">\r\n");
      out.write("                    <input type=\"submit\" value=\"尾 页\" class=\"button\">\r\n");
      out.write("                    &nbsp;&nbsp;&nbsp;\r\n");
      out.write("                    <a >第</a>\r\n");
      out.write("                    <input type=\"text\" style=\"width: 30px;\">\r\n");
      out.write("                    <a >页</a>\r\n");
      out.write("                    <input type=\"submit\" value=\"跳转\" class=\"button\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"bottom\">\r\n");
      out.write("        <div id=\"bottom_text\">\r\n");
      out.write("            <a>\r\n");
      out.write("                版权所有 2011 重庆文理学院 地址: 重庆市永川区红河大道319号 邮编: 402160</br>\r\n");
      out.write("                校友会电话：023-49891798 校办电话：023-49891910\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"admin\">管理登录</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
