/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-04-19 09:30:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import message.domain.AdmissionInformation;
import java.util.List;
import java.util.ArrayList;
import message.dao.impl.AdmissionInformationDaoImpl;
import java.util.LinkedList;
import message.dao.AdmissionInformationDao;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>专业分数查看-首页</title>\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width,initial-scale=1,user-scalable=0\">\r\n");
      out.write("<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<!-- 可选的 Bootstrap 主题文件(一般不用引入) -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"top\">\r\n");
      out.write("\t\t<a>请输入您的高考信息</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"info\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ServletList\" method=\"post\">\r\n");
      out.write("\t\t\t\t<fieldset class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label>生源地：</label> <select class=\"form-control\" name=\"location\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">--请选择--</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"云南\">云南</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"内蒙\">内蒙</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"北京\">北京</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"四川\">四川</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"宁夏\">宁夏</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"安徽\">安徽</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"山东\">山东</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"山西\">山西</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"广东\">广东</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"广西\">广西</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"新疆\">新疆</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"江苏\">江苏</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"江西\">江西</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"河北\">河北</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"河南\">河南</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"浙江\">浙江</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"海南\">海南</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"湖北\">湖北</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"湖南\">湖南</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"甘肃\">甘肃</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"福建\">福建</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"西藏\">西藏</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"贵州\">贵州</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"辽宁\">辽宁</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"重庆\">重庆</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"陕西\">陕西</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"黑龙江\">黑龙江</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<fieldset class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label>文理科</label> <select class=\"form-control\" name=\"type\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"文\">文科</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"理\">理科</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<fieldset class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label>查询专业：</label> <select class=\"form-control\" name=\"major\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">--请选择--</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"会展经济与管理\">会展经济与管理</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"体育教育(师范)\">体育教育(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"信息与计算科学(金融软件)\">信息与计算科学(金融软件)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"信息工程\">信息工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"制药工程\">制药工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"动画\">动画</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"化学工程与工艺\">化学工程与工艺</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"化学(师范)\">化学(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"园林\">园林</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"园林(景观设计)\">园林(景观设计)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"学前教育(师范)\">学前教育(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"学前教育(师范)对口本科\">学前教育(师范)对口本科</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"小学教育(全科教师)\">小学教育(全科教师)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"少数民族本科预科\">少数民族本科预科</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"工商管理\">工商管理</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"工商管理(旅游管理)\">工商管理(旅游管理)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"工商管理(旅游管理) 对口本科\">工商管理(旅游管理) 对口本科</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"工商管理(物流管理)\">工商管理(物流管理)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"工商管理(酒店管理)\">工商管理(酒店管理)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"工程管理\">工程管理</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"工程管理(工程造价)\">工程管理(工程造价)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"广播电视编导\">广播电视编导</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"广播电视编导(文化遗产传播)\">广播电视编导(文化遗产传播)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"应用心理学\">应用心理学</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"思想政治教育(师范)\">思想政治教育(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"数学与应用数学(师范)\">数学与应用数学(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"数学与应用数学(金融数学\">数学与应用数学(金融数学)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"服装设计与工程\">服装设计与工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"机械工程\">机械工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"机械工程对口本科\">机械工程对口本科</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"机械电子工程\">机械电子工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"材料成型及控制工程\">材料成型及控制工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"汉语言文学(师范)\">汉语言文学(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"汉语言文学(现代文秘)\">汉语言文学(现代文秘)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"法学\">法学</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"环境科学(环境治理工程)\">环境科学(环境治理工程)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"环境设计\">环境设计</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"生物科学(师范)\">生物科学(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"电子信息科学与技术\">电子信息科学与技术</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"电子信息科学与技术(微电子制造工程)\">电子信息科学与技术(微电子制造工程)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"电子信息科学与技术对口本科\">电子信息科学与技术对口本科</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"电气工程与自动化\">电气工程与自动化</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"社会体育指导与管理(保健康复)\">社会体育指导与管理(保健康复)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"社会体育指导与管理\">社会体育指导与管理</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"经济统计学\">经济统计学</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"网络工程\">网络工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"网络工程(物联网技术)\">网络工程(物联网技术)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"美术学\">美术学</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"舞蹈学(师范)\">舞蹈学(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"英语(商务英语)\">英语(商务英语)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"英语(师范)\">英语(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"行政管理\">行政管理</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"行政管理对口本科\">行政管理对口本科</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"视觉传达设计\">视觉传达设计</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"计算机科学与技术对口本科\">计算机科学与技术对口本科</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"财务管理\">财务管理</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"软件工程\">软件工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"金属材料工程\">金属材料工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"音乐学(师范)\">音乐学(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"音乐学(师范)\">音乐学(师范)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"音乐学(音乐表演)\">音乐学(音乐表演)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"风景园林\">风景园林</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"食品科学与工程\">食品科学与工程</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"高分子材料与工程\">高分子材料与工程</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-success form-control\">提交</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"result.jsp\">result</a>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"bottom\" style=\"margin-top: 200px\">\r\n");
      out.write("\t\t<a>各省各批次录取最低分请查询招生信息网</a> <a href=\"http://zb.cqwu.net\">http://zb.cqwu.net</a></br>\r\n");
      out.write("\t\t<a>咨询电话：023-49891968 49891969</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
